### ISSUE TITLE
User tracking (Internal)

### ISSUE THREAD

**Issue by IronRunes** [level73/membernet#139]
Requirements
- [x] Inactive users: users that have not logged in for 7 days (adjustable)
- [x] last login time
- [x] record & display session duration (individual session duration) (**ONLY FOR ONETEAM**)

- [x] Create a User tracking dashboard
- [ ] Filtering functionality - 
- - [ ] Members/Non-members 
- - [x] Search by email account

**Comment by IronRunes** [comment]
Hey @decasadecasa  I've implemented this, pretty much. It would be good to have a preliminary review before I delve into the search/filtering functionality. you can access it at the /metrics URL. Please let me know if you have any comments.
