### ISSUE TITLE
user tracking on mnet tweaking 

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#157]
**few notes/requests-** let me know if something is not feasible:
**-filtering by headings (clicking on them to rearrange lists)** please make clicking the headers arrange the IDs from smallest to largest ; username alphabetically; and last log-in from first to last date (and vice versa for all upon second click). it appears to work for email, org, and # of log-ins.
**-separating non-member users:** would it be possible to have a tag under orgs for non-members? right now it shows up blank but would be nice to have it read non-member account or something similar
**-resizing/moving the headers:** the stats and access log headers are spaced in a way which is not making it clear what they are referring to, please move them closer to the appropriate fields
**-adding a regional tab:** to show what region the account is connected to, so we can have an idea of regional engagement (unless you think this is better handled by google analytics)
**-make some clarification/text** that indicates what the field in red under log-in means (inactive over 7 days)

**Comment by decasadecasa** [comment]
another point:
-would it be possible to separate the lists into two? first, one for staff, and then another list for members and non member accounts (that are not staff), but only displaying the accounts that have logged in so we dont have a massive list of just inactive ones

**Comment by IronRunes** [comment]
- [x] Main Access Log Table Sorting: 
- - [x] Username Alphabetical sort check (Hilde showing up first)
- - [ ] Date sort for Last Login
- [x] Separating Non-Members
- - [x] Double list (tabbed): Members & Non-members (hilighting non-members in cell), ILC Staff
- [ ] Regional Tabs/Breakdowns 
- [x] Clarification text for Red Logins
- [ ] Clarify header position/relevant content

**Comment by IronRunes** [comment]
@decasadecasa This stuff can all be done, the heavy lifting is around the staff/members/non-members separation and the regional aggregates/breakdowns. 
These tasks above amount to about a day of work. 
I'll get to work on the simpler ones in the meantime

**Comment by decasadecasa** [comment]
Hi, another question about the feasibility of a feature: 

in the MANAGE USERS tab- we can search and see accounts. Would it be possible to add the last log-in date per user to this section? this way we can check and search by all accounts, and not be limited to just seeing the ones who have logged in recently/create a big list that will get increasingly hard to get through. Let me know, thanks

**Comment by IronRunes** [comment]
sure. breaking this off in another issue as it is not connected to the metrics per se

**Comment by IronRunes** [comment]
added issue #185
